package us.idinfor.smartcitizen.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import us.idinfor.smartcitizen.model.Context;

import us.idinfor.smartcitizen.model.ContextDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contextDaoConfig;

    private final ContextDao contextDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contextDaoConfig = daoConfigMap.get(ContextDao.class).clone();
        contextDaoConfig.initIdentityScope(type);

        contextDao = new ContextDao(contextDaoConfig, this);

        registerDao(Context.class, contextDao);
    }
    
    public void clear() {
        contextDaoConfig.getIdentityScope().clear();
    }

    public ContextDao getContextDao() {
        return contextDao;
    }

}
